version = "0.2"
license = "GPL"
package = "sci"
title = "Scientific and Mathematical Functions"
date = "15 October 2015"
authors = "Gilberto Camara"
contact = "gilberto.camara@inpe.br"
content = "Implements useful mathematical functions"
