version = "0.5"
license = "GPL"
package = "sci"
title = "Scientific and Mathematical Functions"
date = "6 Feb 2017"
depends = "terrame (>= 2.0)"
authors = "Gilberto Camara"
contact = "gilberto.camara@inpe.br"
content = "Implements useful mathematical functions"
